#!/usr/bin/env python3
"""
Paper 4 Validation — Section B: Kappa Computation
Run locally in terminal after receiving validation_sample_coded.xlsx from coder.

Usage:
    python3 compute_kappa.py --coded /path/to/validation_sample_coded.xlsx

Output:
    kappa_results.xlsx   — saved in same folder as the coded file
    Prints numbers ready to paste into Section 3.4
"""

import argparse
import sys
from pathlib import Path

import pandas as pd
from sklearn.metrics import cohen_kappa_score

STRATEGY_CATEGORIES = [
    'pivot', 'experimentation', 'customer_discovery', 'resource_substitution',
    'sequencing', 'scaling', 'optimization', 'capability_building',
    'partnering', 'legitimation'
]

def clean_label(x):
    if pd.isna(x) or str(x).strip() in ('', '(none)', 'none', 'NONE', 'None', 'nan'):
        return 'none'
    return str(x).strip().lower().replace(' ', '_').replace('strategy_', '')

def safe_kappa(x, y):
    if x.sum() == 0 and y.sum() == 0:
        return float('nan')
    try:
        return round(cohen_kappa_score(x, y), 3)
    except Exception as e:
        return float('nan')

def interpret(k):
    if pd.isna(k):       return 'N/A (no positive cases)'
    if k < 0.20:         return 'Poor'
    if k < 0.40:         return 'Fair'
    if k < 0.60:         return 'Moderate'
    if k < 0.80:         return 'Substantial'
    return 'Near-perfect'

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--coded', required=True,
                        help='Path to validation_sample_coded.xlsx')
    args = parser.parse_args()

    coded_path = Path(args.coded)
    if not coded_path.exists():
        sys.exit(f'ERROR: file not found: {coded_path}')

    out_path = coded_path.parent / 'kappa_results.xlsx'

    # ── Load coded file ──────────────────────────────────────────
    print(f'\nLoading: {coded_path}')
    coded   = pd.read_excel(coded_path, sheet_name='Sample')
    try:
        ref = pd.read_excel(coded_path, sheet_name='_reference_regex')
    except Exception:
        sys.exit('ERROR: _reference_regex sheet not found in coded file.\n'
                 'Make sure you are using the file generated by Section A of the notebook, '
                 'not a manually created one.')

    merged = coded.merge(ref, on='row_id', how='left')

    # ── Check for required columns ────────────────────────────────
    for col in ['pass_A_label', 'pass_B_label']:
        if col not in merged.columns:
            sys.exit(f'ERROR: column "{col}" not found in Sample sheet.\n'
                     f'Available columns: {merged.columns.tolist()}')

    # ── Clean labels ─────────────────────────────────────────────
    merged['A'] = merged['pass_A_label'].apply(clean_label)
    merged['B'] = merged['pass_B_label'].apply(clean_label)
    merged['R'] = merged['regex_label'].apply(clean_label)

    # ── Check for typos ──────────────────────────────────────────
    valid = set(STRATEGY_CATEGORIES) | {'none'}
    for col, name in [('A', 'Pass A'), ('B', 'Pass B')]:
        bad = merged[~merged[col].isin(valid)]
        if len(bad):
            print(f'\nWARNING: {name} has {len(bad)} unrecognized labels:')
            for _, r in bad.iterrows():
                print(f'  row {r["row_id"]}: "{r[col]}"')
            print(f'  Valid labels: {sorted(STRATEGY_CATEGORIES)}')
            print(f'  Fix these in the Excel file and re-run.\n')

    n = len(merged)
    print(f'\nSample size: {n}')
    print(f'Pass A labeled: {(merged["A"] != "none").sum()} / {n}')
    print(f'Pass B labeled: {(merged["B"] != "none").sum()} / {n}')
    print(f'Regex labeled:  {(merged["R"] != "none").sum()} / {n}')

    # ── Overall kappa ─────────────────────────────────────────────
    k_ab = safe_kappa(
        merged['A'].factorize()[0],
        merged['B'].factorize()[0]
    )
    # For A vs R and B vs R, re-factorize together so labels align
    def kappa_pair(s1, s2):
        combined = pd.concat([s1, s2])
        cats = sorted(combined.unique())
        c1 = pd.Categorical(s1, categories=cats).codes
        c2 = pd.Categorical(s2, categories=cats).codes
        return safe_kappa(pd.Series(c1), pd.Series(c2))

    k_ar = kappa_pair(merged['A'], merged['R'])
    k_br = kappa_pair(merged['B'], merged['R'])

    overall = pd.DataFrame([
        {'Comparison': 'Pass A (strict) vs Pass B (permissive)',
         'Kappa': k_ab, 'n': n, 'Interpretation': interpret(k_ab)},
        {'Comparison': 'Pass A (strict) vs Regex classifier',
         'Kappa': k_ar, 'n': n, 'Interpretation': interpret(k_ar)},
        {'Comparison': 'Pass B (permissive) vs Regex classifier',
         'Kappa': k_br, 'n': n, 'Interpretation': interpret(k_br)},
    ])

    print('\n' + '='*60)
    print('OVERALL KAPPA RESULTS')
    print('='*60)
    for _, r in overall.iterrows():
        k_str = f"{r['Kappa']:.3f}" if not pd.isna(r['Kappa']) else 'N/A'
        print(f"  {r['Comparison']}")
        print(f"    kappa = {k_str}  ({r['Interpretation']})")

    # ── Per-category kappa ────────────────────────────────────────
    per_cat = []
    for cat in STRATEGY_CATEGORIES:
        A_bin = (merged['A'] == cat).astype(int)
        B_bin = (merged['B'] == cat).astype(int)
        R_bin = (merged['R'] == cat).astype(int)
        per_cat.append({
            'Category':        cat,
            'n_A_labeled':     int(A_bin.sum()),
            'n_B_labeled':     int(B_bin.sum()),
            'n_regex_in_sample': int(R_bin.sum()),
            'kappa_A_vs_B':    safe_kappa(A_bin, B_bin),
            'kappa_A_vs_regex': safe_kappa(A_bin, R_bin),
            'kappa_B_vs_regex': safe_kappa(B_bin, R_bin),
        })

    per_cat_df = pd.DataFrame(per_cat)

    print('\n' + '='*60)
    print('PER-CATEGORY KAPPA (A vs B, sorted)')
    print('='*60)
    for _, r in per_cat_df.sort_values('kappa_A_vs_B', ascending=False).iterrows():
        k = r['kappa_A_vs_B']
        k_str = f"{k:.3f}" if not pd.isna(k) else ' N/A'
        print(f"  {r['Category']:25s}  kappa_AB={k_str}  "
              f"n_A={int(r['n_A_labeled'])}  n_B={int(r['n_B_labeled'])}  "
              f"n_regex={int(r['n_regex_in_sample'])}")

    # ── Save results ──────────────────────────────────────────────
    with pd.ExcelWriter(out_path, engine='openpyxl') as writer:
        overall.to_excel(writer,   sheet_name='Overall_Kappa',      index=False)
        per_cat_df.to_excel(writer, sheet_name='Per_Category_Kappa', index=False)
        merged[['row_id','sentence_id','text','A','B','R']].to_excel(
            writer, sheet_name='Full_Coded_Data', index=False)

    print(f'\nSaved: {out_path}')
    print('\n=== PASTE THESE INTO SECTION 3.4 ===')
    print(f'Pass A vs Pass B:          kappa = {k_ab:.3f}  n = {n}  ({interpret(k_ab)})')
    print(f'Pass A vs Regex:           kappa = {k_ar:.3f}  n = {n}  ({interpret(k_ar)})')
    print(f'Pass B vs Regex:           kappa = {k_br:.3f}  n = {n}  ({interpret(k_br)})')

if __name__ == '__main__':
    main()
